# -*- coding: utf-8 -*-
"""suggestion_draft2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dwd9Q9I4bHLHciaR-W1xilLIjNwPtYyd
"""

import pandas as pd
import numpy as np

dog_df=pd.read_csv("/content/dogtime.csv")
dog_df = dog_df[['breed','characteristic','star']]

# unstack to columns with breed + 26 characteristics
df=dog_df.set_index(keys=['breed','characteristic'])
df = df.unstack()
df.columns = df.columns.droplevel(0)
df= df.reset_index()
df = df.rename_axis(index=(None), columns=None)

# 3 nan values
# at rows [163, 245, 317]
# [Doxiepoo, Korean Jindo Dog, Puginese]
# ['Drooling Potential', 'Prey Drive', 'Tendency To Bark Or Howl']
# replace nan to 0
df = df.fillna(0)

df[df.columns[1:]] = df[df.columns[1:]].astype(int)
df

# L = np.char.add(list(df.columns[1:]),'`')
# L = np.char.add('`',L)
# L

import string
L1 = list(string.ascii_lowercase)
L2 = list(df.columns[1:])
# we have 26 characteristics
dog_map = dict(zip(L1,L2))
dog_map

def finddog(**characteristics):
  """
  check dog_map
  ex: 'a' is 'Adapts Well To Apartment Living'
  """
  # make default to all 26 characteristics >=0
  characteristic_dict = dict.fromkeys(list(df.columns[1:]), ">=0")

  for key, val in characteristics.items():
    characteristic_dict[dog_map[key]]= val 

  text =\
  """ 
  `Adapts Well To Apartment Living`{Adapts Well To Apartment Living}
  &`Affectionate With Family`{Affectionate With Family}
  &`Amount Of Shedding` {Amount Of Shedding}
  &`Dog Friendly`{Dog Friendly}
  &`Drooling Potential`{Drooling Potential}
  &`Easy To Groom` {Easy To Groom}
  &`Easy To Train` {Easy To Train}
  &`Energy Level` {Energy Level}
  &`Exercise Needs` {Exercise Needs}
  &`Friendly Toward Strangers` {Friendly Toward Strangers}
  &`General Health` {General Health}
  &`Good For Novice Owners` {Good For Novice Owners}
  &`Intelligence`{Intelligence}
  &`Intensity`{Intensity}
  &`Kid-Friendly`{Kid-Friendly}
  &`Potential For Mouthiness`{Potential For Mouthiness}
  &`Potential For Playfulness`{Potential For Playfulness}
  &`Potential For Weight Gain`{Potential For Weight Gain}
  &`Prey Drive`{Prey Drive}
  &`Sensitivity Level`{Sensitivity Level}
  &`Size`{Size}
  &`Tendency To Bark Or Howl`{Tendency To Bark Or Howl}
  &`Tolerates Being Alone`{Tolerates Being Alone}
  &`Tolerates Cold Weather`{Tolerates Cold Weather}
  &`Tolerates Hot Weather`{Tolerates Hot Weather}
  """.format(**characteristic_dict).replace('\n','')

  results = df.query(f'{text}')['breed'].tolist()
  return results

# enter kwargs according to dog_map
finddog(a=">=2", b= '==3',f = '>=2', z='<=4', c='==3')